### ISSUE TITLE
Different timestamp minutes in multi-module project

### ISSUE THREAD

**Issue by achevin-murex** [smartcodeltd/release-candidate-maven-plugin#12]
I face the issue that the parent and one child don't have the same minute in their timestamp.
It leads to missing artifact when I want to retrieve them from the nexus.

I configure the release candidate plugin from the command line only. I run:

```
mvn com.smartcodeltd:release-candidate-maven-plugin:1.0-201603091838.01dbbbf:updateVersion 
-DreleaseVersionFormat="{{ api_version }}-{{ timestamp('YYYYMMddHHmm') }}"
```

Could this be the problem?

Thank you!
A

**Comment by jan-molak** [comment]
Hey @achevin-murex, would you be able to reproduce the problem in a [unit test](https://github.com/smartcodeltd/release-candidate-maven-plugin/tree/master/src/it)?

**Update**: I think I understand the issue based on the original title of this ticket "when the build is overlapping two minutes". The latest build should resolve this problem.

**Update 2**: The new build (1.0-201605132325.9e7d5be) is now available on both Bintray and Maven Central, please update and let me know if the issue is resolved please.

**Comment by achevin-murex** [comment]
Hello @jan-molak,

I've reproduced the problem manually (by waiting for the end of a minute before running maven :-)).
I don't know how to play with the time to unit test this.
I verified your fix the same way and it worked.

Thank you!
A

**Comment by philou** [comment]
Hi, I'm working in @achevin-murex team, and we had the issue again today. Here is the log :

``` log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] XXXX-utils-root
[INFO] POP :: XXXX UTILS
[INFO] POP :: XXXX TEST UTILS
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building XXXX-utils-root 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- release-candidate-maven-plugin:1.0-201605132325.9e7d5be:updateVersion (default-cli) @ XXXX-utils-root ---
[INFO] Setting version to: '1.0-201605191753.e96e2e3'
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building POP :: XXXX UTILS 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: ...
[INFO] 
[INFO] --- release-candidate-maven-plugin:1.0-201605132325.9e7d5be:updateVersion (default-cli) @ XXXX-utils ---
[INFO] Setting version to: '1.0-201605191754.e96e2e3'
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building POP :: XXXX TEST UTILS 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- release-candidate-maven-plugin:1.0-201605132325.9e7d5be:updateVersion (default-cli) @ XXXX-test-utils ---
[INFO] Setting version to: '1.0-201605191753.e96e2e3'
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] XXXX-utils-root .................................... SUCCESS [  1.168 s]
[INFO] POP :: XXXX UTILS .................................. SUCCESS [ 12.928 s]
[INFO] POP :: XXXX TEST UTILS ............................. SUCCESS [  0.005 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.839 s
[INFO] Finished at: 2016-05-19T17:54:00+02:00
[INFO] Final Memory: 14M/226M
[INFO] ------------------------------------------------------------------------
```

As you can see, we are using the latest version of the release candidate plugin (1.0-201605132325.9e7d5be), but all versions are set to 1.0-201605191753.e96e2e3 except XXXX UTILS which is set to 1.0-20160519175**4**.e96e2e3.

Thanks a lot,

**Comment by jan-molak** [comment]
Hey @philou and thanks for letting me know. I'll try to look into this over the next couple of weeks, but in the meantime - pull requests are welcome!
