### ISSUE TITLE
Versions are not updated in multi-level Maven project

### ISSUE THREAD

**Issue by piotrgwiazda** [smartcodeltd/release-candidate-maven-plugin#14]
In case of project striucture
`project-root
     project-parent
     project-module-a
     project-module-b`

where project-parent is a parent POM for project-module-a and project-module-b (relativePath `../project-parent/pom.xml`) the versions of parent pom in project-module-a and project-module-b are not updated

**Comment by jan-molak** [comment]
Hey @piotrgwiazda and thanks for letting me know! Would you mind [creating a test case](https://github.com/smartcodeltd/release-candidate-maven-plugin/tree/master/src/it) to demonstrate the issue?

Many thanks,
Jan

**Comment by piotrgwiazda** [comment]
Sure but won't have time today. It's the same case as
https://github.com/smartcodeltd/release-candidate-maven-plugin/tree/master/src/it/updateVersion_multi-module
but make "first" be parent of "second"
1 wrz 2016 11:33 "Jan Molak" notifications@github.com napisał(a):
