### ISSUE TITLE
Mark @threadSafe

### ISSUE THREAD

**Issue by jonfreedman** [smartcodeltd/release-candidate-maven-plugin#18]
If possible it would be great to mark this plugin `@threadSafe` to fix the build warnings:

```
The following plugins are not marked @threadSafe in common:
com.smartcodeltd:release-candidate-maven-plugin:1.0-201609171818.3e8187b
```

**Comment by jan-molak** [comment]
Hey @jonfreedman - sure, would you mind raising a PR?

**Comment by jonfreedman** [comment]
I'll see if I can figure out which line needs changing

**Comment by jonfreedman** [comment]
Thanks for merging, any idea when you'll cut a release?

**Comment by jan-molak** [comment]
As soon as I migrate the CI process from CloudBees Dev@Cloud, which has ceased to exist, to Travis... I haven't touched Release Candidate in something like 3-4 years, so need to remember what the past Jan has done here ;-)

Bear with me.

**Comment by jan-molak** [comment]
OK, there are still some glitches with the build process that I'll sort out tomorrow, but the new artifact should already be available on JCenter.

**Comment by jan-molak** [comment]
All issues are now sorted out. Thanks for helping me make Release Candidate better, @jonfreedman 👍

**Comment by jonfreedman** [comment]
I'm not sure that 1.0-201910011043.383523b made it onto maven central, your download badge is still pointed @ https://bintray.com/jan-molak/maven/release-candidate-maven-plugin/1.0-201609171818.3e8187b

**Comment by jan-molak** [comment]
Apologies, my bad. I forgot that the artifact needs to be manually synced between Bintray and Maven central. The latest version should be available shortly.

**Comment by jonfreedman** [comment]
Thank you for getting this into central, maven build warning is history!

**Comment by jan-molak** [comment]
Splendid! Thanks for your help :-)
