### ISSUE TITLE
Project doesn't build on Windows platform

### ISSUE THREAD

**Issue by cdelmas** [smartcodeltd/release-candidate-maven-plugin#3]
When building on a Windows machine, some tests fail because of comparison failure due to difference between eol on Windows and Linux platforms (\r\n vs \n only).

As an attachment, the console trace.
[console.txt](https://github.com/smartcodeltd/release-candidate-maven-plugin/files/79540/console.txt)

**Comment by jan-molak** [comment]
Hey @cdelmas and many thanks for reporting this, let me have a look :-)

**Comment by cdelmas** [comment]
If it can help, I tried to figure out where is the problem: you have to use System.getProperty("line.separator") in the class Difference instead of hardcoded \n. This fixes some tests.
For the remaining, it seems that the problem resides somewhere in the  maven-plugin-testing-harness that doesn't handle well the line endings read from the pom of the teamcity-integration project.

**Comment by jan-molak** [comment]
@cdelmas, it should be now possible to build the project on Windows platform, many thanks for reporting the issue! :+1:
