### ISSUE TITLE
Parent version is updated, but should not

### ISSUE THREAD

**Issue by cdelmas** [smartcodeltd/release-candidate-maven-plugin#5]
In the case of an organization pom, the parent's version should not be changed. For example, in https://github.com/apache/spark/blob/master/pom.xml, the version of org.apache:apache should not be changed.
I think we can tell that when the parent's group and/or version is not the same as the project group/version, it should not be changed. Or maybe it is a matter of SNAPSHOT (when the parent's version is not a SNAPSHOT, it should not be changed)?
Whatever the choice (or even you can let the user choose), it should be controlled by a property, with a default behavior.

**Comment by jan-molak** [comment]
Thanks, it seems like you already have an idea for a solution :smile: Maybe we could discuss it over a pull request?

**Comment by cdelmas** [comment]
I have a working basic solution on my repo. Will make a pull request as soon as the other will be closed (seems like I can't make another pull request at this time).
For the moment, I just handle the case where the parent pom is not an organization pom, has the same group id and has a snapshot version (not the same is accepted). I added a test case too. You can check it out if you want a preview.

**Comment by jan-molak** [comment]
I think this one's now closable based on your latest pull request? #4

**Comment by cdelmas** [comment]
Yes, I think we can close it, unless we want to go further. Thank you!
